login/urls.py
from django.urls import path
from login.views import register, basic, profile, logout1
from musicapp import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', basic, name="basic"),
    path('register/', register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='login/login.html'), name="login"),
    path('logout/', logout1, name="logout"),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='login/password_reset.html'), name="reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='login/password_reset_done.html'), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='login/password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='login/password_reset_complete.html'), name="password_reset_complete"),
    path('profile/', profile, name='profile'),
    
]


if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL,
                          #document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

musicapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("login.urls")),
    path('', include(("playlist.urls", 'playlist'), namespace='playlist'))
]

playlist/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import rejectrequest, followers, updateplaylist,playsonglist, sortbydate, sortbyartist, sortbytitle, ViewPlaylist, homepage, createplaylist, Playlists, EditPlaylist, addsong, updatesong, deletesong, deleteplaylist, searchuser, followuser, unfollowuser, userdashboard, copysong, transfersong, copysongtoplay, transfersongtoplay
app_name = "playlist"
urlpatterns = [
    path('home/', Playlists.as_view(), name="home" ),
    path('createplaylist/', createplaylist, name="playlist"),
    path('editplaylist/<int:pk>', EditPlaylist.as_view(), name="edit"),
    path('addsong/<int:pk>', addsong , name="addsong"),
    path('updatesong/<int:pid>/<int:pk>', updatesong, name="updatesong"),
    path('updateplaylist/<int:pid>', updateplaylist, name="updateplaylist"),
    path('deletesong/<int:pid>/<int:pk>', deletesong, name="deletesong"),
    path('deleteplaylist/<int:pid>', deleteplaylist, name="deleteplaylist"),
    path('searchuser', searchuser, name="searchuser"),
    path('follow/<int:userid>', followuser, name="followuser"),
    path('unfollow/<int:userid>', unfollowuser, name="unfollowuser"),
    path('userdashboard/<int:userid>', userdashboard, name="userdahboard"),
    path("copysong/<int:pid>", copysong, name="copysong"),
    path("transfersong/<int:pid>", transfersong, name="transfersong"),
    path("copysongtoplay/<int:pid>", copysongtoplay, name="copysongtoplay"),
    path("transfersongtoplay/<int:pid>", transfersongtoplay, name="transfersongtoplay"),
    path("sortbydate/<int:pid>", sortbydate, name="sortbydate"),
    path("sortbyartist/<int:pid>", sortbyartist, name="sortbyartist"),
    path("sortbytitle/<int:pid>", sortbytitle, name="sortbytitles"),
    path("detailview/<int:userid>/<int:pk>",ViewPlaylist.as_view(), name="viewdetails"),
    path("playlists/", playsonglist.as_view(), name="playlists"),
    path("followers/", followers, name="followers"),
    path("rejectrequest/<int:userid>",rejectrequest, name="reject" )

]

playlist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

CHOICES = ((0, 'Private'),
                  (1, 'Public'),
                  (2, 'FollowersOnly'),
                  )
class Song(models.Model):
    sid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=1000)
    artist = models.CharField(max_length=1000)
    mp3 = models.FileField('Track File',upload_to="track/")
    status = models.IntegerField(choices=CHOICES, default=0)
    date_added = models.DateTimeField(default=timezone.now(), blank=True, null=True)
    objects = models.Manager()
    def __str__(self):
        return self.title

class Playlist(models.Model):
    pid = models.AutoField(primary_key = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 1000)
    songs = models.ManyToManyField(Song)
    status = models.IntegerField(choices=CHOICES, default=0)
    logo = models.FileField()
    date_created = models.DateTimeField(default = timezone.now())
    objects = models.Manager()
    def __str__(self):
        return self.title

playlist/forms.py
from .models import Playlist, Song
from django import forms
class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ['title','logo','status']

class UpdatePlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ['title', 'logo', 'status']

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['title', 'artist', 'status', 'mp3']

class UpdateSongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['title', 'artist', 'status', 'mp3']

playlist/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from playlist.forms import PlaylistForm, SongForm, UpdateSongForm, UpdatePlaylistForm
from .models import Playlist, Song
from login.models import Profile
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.db.models.functions import Lower
from .serializers import playlistsongserializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
# Create your views here.


AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def homepage(request):
    return render(request, 'playlist/home.html')

@login_required
def createplaylist(request):
    if(request.method == "POST"):
        form = PlaylistForm(request.POST or None, request.FILES or None)
        p = Playlist.objects.filter(user = request.user)
        if form.is_valid():
            new = form.save(commit=False)
            new.user = request.user
            file_type = new.logo.url.split(".")[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                messages.error(request, "Image file must be jpg, jpeg or png!")
                return render(request, "playlist/createplaylist.html", {"form": form})
            #Each playlist should have different title
            for play in p:
                if(play.title == new.title):
                    messages.warning(request, f"Playlist with {play.title} as title already exists!")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
            new.save()
            messages.success(request, new.title + " playlist created successfully!!")
            return redirect("/home")
        else:
            messages.error(request, "playlist could not be created")
    else:
        
        form = PlaylistForm()
    return render(request, 'playlist/createplaylist.html', {'form': form})

def playlistid(id):
    q = Playlist.objects.filter(pid = id)
    return q[0]

def addsong(request, pk):
    if(request.method == "POST"):
        form = SongForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            #check audiofile extensions
            f = form.save(commit = False)
            x = Playlist.objects.get(pid = pk)
            s = Song(title = request.POST.get("title"), artist = request.POST.get("artist"), mp3 = request.FILES.get("mp3"), status = request.POST.get("status"))
            file_type = f.mp3.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in AUDIO_FILE_TYPES:
                messages.error(request, "Audio file must be WAV, MP3, or OGG!")
                return render(request, "playlist/songform.html", {"form": form})
            s.save()
            x.songs.add(s)
            messages.success(request, s.title +
                             " song added successfully!!")
            return redirect(f"/editplaylist/{pk}")
        else:
            messages.error(request, "playlist could not be created")
    else:
        form = SongForm()
        return render(request, "playlist/songform.html",{"form":form})

def updatesong(request, pid, pk):
    if(request.method == "POST"):
        s = Song.objects.get(sid=pk)
        form = UpdateSongForm(request.POST, request.FILES, instance = s)
        if form.is_valid():
            #check audiofile extensions
            x = form.save(commit=False)
            x.save()
            messages.success(request, x.title +
                             " song updated successfully!!")
            return redirect(f"/editplaylist/{pid}")
        else:
            messages.error(request, "Song could not be updated!!")
            return redirect(f"/editplaylist/{pid}")
    else:
        s = Song.objects.get(sid=pk)
        form = UpdateSongForm(instance = s )
        return render(request, "playlist/songform.html", {"form": form, "update":1})


def updateplaylist(request, pid):
    if(request.method == "POST"):
        s = Playlist.objects.get(pid = pid)
        form = UpdatePlaylistForm(request.POST, request.FILES, instance=s)
        if form.is_valid():
            new = form.save(commit=False)
            new.user = request.user
            file_type = new.logo.url.split(".")[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                messages.error(request, "Image file must be jpg, jpeg or png!")
                return render(request, "playlist/createplaylist.html", {"form": form, "update":1})
            new.save()
            messages.success(request, new.title +
                             " playlist updated successfully!!")
            return redirect(f"/editplaylist/{pid}")
        else:
            messages.error(request, "Playlist could not be updated!!")
            return redirect(f"/editplaylist/{pid}")
    else:
        s = Playlist.objects.get(pid = pid)
        form = UpdatePlaylistForm(instance=s)
        return render(request, "playlist/createplaylist.html", {"form": form, "update": 1})

def deletesong(request, pid, pk):
    x = Playlist.objects.get(pid = pid)
    k = Song.objects.filter(sid = pk)
    x.songs.remove(k[0])
    messages.success(request, f"{k[0].title} song successfully removed from {x.title} playlist!!")
    return redirect(f"/editplaylist/{pid}")

def deleteplaylist(request, pid):
    x = Playlist.objects.filter(pid = pid)
    title = x[0].title
    x[0].delete()
    messages.success(
        request, f"{title} playlist successfully deleted!!")
    return redirect(f"/home")

@login_required
def followuser(request, userid):
    u = User.objects.get(id = userid)
    #print(u)
    u.profile.followers.add(request.user)
    request.user.profile.following.add(u)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def unfollowuser(request, userid):
    u = User.objects.get(id=userid)
    #print(u)
    u.profile.followers.remove(request.user)
    request.user.profile.following.remove(u)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def userdashboard(request, userid):
    user = User.objects.get(id = userid)
    followers = user.profile.followers.all()
    p = Playlist.objects.filter(user__id = userid)
    playlistcount = p.count()
    pl = p.filter(status = 1)
    if(request.user in followers):
        pl = p.filter(Q(status = 1) | Q(status = 2))
    return render(request, "playlist/userdashboard.html", {"user":user, "playlists":pl, "plcount":playlistcount})

@login_required
def copysong(request, pid):
    #returns pid, lists of playlists, list of song for each playlist
    albumid = pid
    album = Playlist.objects.filter(pid = pid)
    playlists = Playlist.objects.filter(user = request.user).exclude(pid = pid)
    songdict = {}
    for p in playlists:
        l = []
        if(p.pid != pid):
            for k in p.songs.all():
                if(k not in album[0].songs.all()): #do not show list of songs which are already present in the current playlist
                    l.append([k.title, k.sid])
            songdict["playlist" + p.title] = l
    
    return render(request, "playlist/copysong.html", {"albumid":albumid, "playlists":playlists, "songdict":songdict, "copysong":1})


@login_required
def copysongtoplay(request, pid):
    l = [int(i) for i in request.POST.getlist("choices[]")] #id of songs to be copied
    p = Playlist.objects.get(pid = pid)
    for x in l:
        s = Song.objects.filter(sid = x)
        p.songs.add(s[0])
    messages.success(request, "Songs copied successfully")
    return redirect(f"/editplaylist/{pid}")

@login_required
def transfersong(request, pid):
    albumid = pid
    playlists = Playlist.objects.filter(user = request.user).exclude(pid = pid)
    print(playlists)
    album = Playlist.objects.filter(pid=pid)
    songs = album[0].songs.all()
    return render(request, "playlist/transfersong.html", {"albumid": albumid, "playlists": playlists, "songs": songs, })


@login_required
def transfersongtoplay(request, pid):
    lp = [int(i) for i in request.POST.getlist(
        "choices[]")]  # id of playlists in which selected songs are to be copied
    ls = [int(i) for i in request.POST.getlist("songs")]
    s = []
    for x in ls:
        q = Song.objects.get(sid = x)
        s.append(q)
    
    for p in lp:
        play = Playlist.objects.get(pid = p)
        for d in s:
            if(d not in play.songs.all()):
                play.songs.add(d)
            else:
                messages.warning(request, f"{d.title} song already present in current playlist!")
    #delete the song from current playlist
    for d in s:
        Playlist.objects.get(pid = pid).songs.remove(d)
    messages.success(request, "Songs transferred successfully")
    return redirect(f"/editplaylist/{pid}")


@login_required
def sortbydate(request, pid):
    songs = Playlist.objects.get(pid = pid).songs.all()
    songs = songs.order_by("-date_added")
    album = Playlist.objects.get(pid = pid)
    return render(request, "playlist/editplaylist.html", {"songs":songs, "album":album})

@login_required
def sortbyartist(request, pid):
    songs = Playlist.objects.get(pid=pid).songs.all()
    songs = songs.order_by(Lower("artist"))
    album = Playlist.objects.get(pid=pid)
    return render(request, "playlist/editplaylist.html", {"songs": songs, "album": album})


@login_required
def sortbytitle(request, pid):
    songs = Playlist.objects.get(pid=pid).songs.all()
    songs = songs.order_by(Lower("title"))
    album = Playlist.objects.get(pid=pid)
    return render(request, "playlist/editplaylist.html", {"songs": songs, "album": album})

class Playlists(ListView):
    model = Playlist

playlist/templates/playlist/copysong.html
{% extends 'login/basic.html' %} {%block head%}
<style type="text/css">
    form.demoForm {
        margin: 2em 0 3em;
    }
    
    form.demoForm select {
        vertical-align: top;
        margin-right: 1em;
    }
    
    select#choices {
        min-width: 140px;
    }
</style>
{%endblock%} {%block title%}Copy song {{albumid}}{% endblock%} {%block body%}
<!--copysongtoplaylist/{{album.id}}-->
<div class="container" style="margin-top: 3%; margin-left: 3%">
    <div class="row p-3 mb-2 bg-dark text-white">
        <form action="/copysongtoplay/{{albumid}}" method="post" id="demoForm" class="demoForm">
            {% csrf_token %}
            <strong>Select playlist:</strong>
            <select name="category" class="form-control col-md-6 mt-3 mb-3"> <!--list of playists-->
    {% for p in playlists%}
    <option value="playlist{{p.title}}">{{p.title}}</option>
    {% endfor %}
    </select>
            <strong>Select songs:</strong>
            <select name="choices[]" id="choices" multiple="multiple" class="form-control col-md-6 my-3">
    <!-- js populates -->
    </select>
            <p class="text-muted">Press Ctrl for selecting multiple songs</p>
            <button type="submit" class="btn btn-outline-success my-3">Copy songs</button>
        </form>
    </div>
</div>
{%endblock%} {% block js%}
<script>
    function appendDataToSelect(sel, obj) {

        for (var i = 0; i < obj.length; i++) {
            var optn = obj[i];
            var el = document.createElement("option");
            el.textContent = optn[0];
            el.value = optn[1];
            sel.appendChild(el);


        }
    };

    document.forms['demoForm'].elements['category'].onchange = function(e) {
        // name of associated select list
        var relName = 'choices[]';

        // reference to associated select list 
        var relList = this.form.elements[relName];

        // get data from object literal based on selection in controlling select list (this.value)
        var obj = Select_List_Data[this.value];
        //console.log(obj)
    };

    var Select_List_Data = {{songdict | safe}}; //dictionary of the form {"playlist"+playlist_name:[list of songs]}
    // populate associated select list when page loads
    window.onload = function() {
        var form = document.forms['demoForm'];

        // reference to controlling select list
        var sel = form.elements['category'];
        //sel.selectedIndex = 0;
        console.log("sel", sel.value)
            // name of associated select list
        var relName = 'choices[]';
        // reference to associated select list
        var rel = form.elements[relName];

        // get data for associated select list passing its name
        // and value of selected in controlling select list
        var data = Select_List_Data[sel.value];
        console.log("data", data)
            // add options to associated select list
        appendDataToSelect(rel, data);
    };
</script>
{% endblock %}

playlist/templates/playlist/createplaylist.html
{% extends 'login/basic.html' %}
{% block title %} Playlist {% endblock %}
{%load crispy_forms_tags%}
{% block body %}
     <div class="container" style="margin-top: 3%; margin-left: 3%">
        <div class="row p-3 mb-2 bg-dark text-white">
                <div class="col-md-6" style="margin-top: 1%">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %} 
                    <fieldset class="form-group">
                        <legend class='border-bottom mb-4'>
                            Add Playlist
                        </legend>
                        {{form | crispy}}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">
                            {%if update%}
                            Update Playlist
                            {%else%}
                            Add Playlist
                            {%endif%}
                            </button>
                    </div>
                    </form>


                </div>
        </div>
    </div>
        
{% endblock %}

playlist/templates/playlist/detailview.html
{% extends 'login/basic.html'%}
{% block title%} DetailView {{album.pid}}{%endblock%}
{% block body %}
<div class="container">
{% if public_songs %}
    <h1 style="color:pink">Public Songs</h1>
    <table class="table table-sm table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Song Title</th>
      <th scope="col">Artist</th>
      <th scope="col">Audio File</th>
    </tr>
  </thead>
   <tbody>
  {% for p in public_songs %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{p.title}}</td>
      <td>{{p.artist}}</td>
      <td><a target="_blank" href="{{ p.mp3.url }}">
                <button type="button" class="btn btn-success btn-xs">
                    <span class="fa fa-play"></span>&nbsp; Play
                </button>
            </a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}

{% if follower_songs %}
    <h1 style="color:pink">Onlyfollower Songs</h1>
    <table class="table table-sm table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Song Title</th>
      <th scope="col">Artist</th>
      <th scope="col">Audio File</th>
    </tr>
  </thead>
   <tbody>
  {% for p in follower_songs %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{p.title}}</td>
      <td>{{p.artist}}</td>
      <td><a target="_blank" href="{{ p.mp3.url }}">
                <button type="button" class="btn btn-success btn-xs">
                    <span class="fa fa-play"></span>&nbsp; Play
                </button>
            </a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}

{% if private_songs %}
    <h1 style="color:pink">Private Songs</h1>
    <table class="table table-sm table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Song Title</th>
      <th scope="col">Artist</th>
      <th scope="col">Audio File</th>
    </tr>
  </thead>
   <tbody>
  {% for p in private_songs %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{p.title}}</td>
      <td>{{p.artist}}</td>
      <td><a target="_blank" href="{{ p.mp3.url }}">
                <button type="button" class="btn btn-success btn-xs">
                    <span class="fa fa-play"></span>&nbsp; Play
                </button>
            </a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}
</div>
{% endblock %}

playlist/templates/playlist/editplaylist.html
{% extends 'login/basic.html' %} 
{%block head%}
<style>

</style>
{% endblock%}
{% block title%}editplaylist{{album.pid}}{% endblock %} {% block body %}

<div class="fluid-container" >
        
            <div class="row mt-3 mx-3">
                <!--Left Panel-->
                <!--Album view-->
                <div class="col-md-3">
                    
                    <div class="panel panel-default">
                        
                        <div class="panel-body">

                            <img src="{{ album.logo.url }}" alt="" width="280" height="280"/>
                            <h1 style="color:#ff33be">{{ album.title }}</h1>
                            <a class="btn btn-info" href="/updateplaylist/{{album.pid}}">Edit Details</a>
                            
                        </div>
                        
                    </div>
                    <!--End of Left Panel-->
                </div>
                 <!--Right View-->
                    <div class="col-sm-8 col-md-9 ">
                        <div class="row">
                            <a class="btn btn-primary"href="/home">View All</a></li>
                                <a href="/addsong/{{album.pid}}" class="btn btn-secondary mx-3"style="font-weight: bold">
                                    <span class="fa fa-plus"></span>
                                    New Song
                                </a>
                                <a href="/copysong/{{album.pid}}" class="btn btn-danger"style="font-weight: bold">
                                    <span class="fa fa-clone"></span>
                                    Copy Songs
                                </a>
                                <a href="/transfersong/{{album.pid}}" class="btn btn-success mx-3"style="font-weight: bold">
                                    <span class="fas fa-file-export"></span>
                                    Transfer Songs
                                </a>
                                <div class="dropdown show">
                                <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="fas fa-sort"></span>
                                    Sort Songs
                                </a>

                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" href="/sortbydate/{{album.pid}}" onchange="this.form.submit()">Date Added</a>
                                    <a class="dropdown-item" href="/sortbyartist/{{album.pid}}" onchange="this.form.submit()">Artist</a>
                                    <a class="dropdown-item" href="/sortbytitle/{{album.pid}}" onchange="this.form.submit()">Title</a>
                                </div>
                                </div>
                                </div>
                        {% if songs%}
                        <div class="panel panel-default mx-4 my-4">

                            <div class="panel-body" >
                                <table class="table" style="color:#77ff33" >
                                    <thead>
                                        <tr>
                                            <th>Title</th>
                                            <th>Artist Name</th>
                                            <th>Audio File</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for song in songs%}
                                            <tr>
                                                <td><strong>{{ song.title }}</strong></td>
                                                <td><strong>{{ song.artist }}</strong></td>
                                            <td>
                                             <a target="_blank" href="{{ song.mp3.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="fa fa-play"></span>&nbsp; Play
                                                </button>
                                             </a>
                                            </td>

                                            <td>

                                            <a class="btn btn-danger" href="/deletesong/{{album.pid}}/{{song.sid}}">
                                            <span class="fa fa-trash"></span>
                                        </a>

									<a class="btn btn-secondary" href="/updatesong/{{album.pid}}/{{song.sid}}">
                                            <span class="fas fa-edit"></span>
                                        </a>


                                            </td>

                                        {% endfor %}
                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>
                
            </div>
            {% endif %}
        </div>
        
{% endblock %}

playlist/templates/playlist/home.html
{% extends 'login/basic.html' %} {% block title%}homepage{% endblock %} {% block body %}

<style>
    img {
        border: 1px solid #ddd;
        /* Gray border */
        border-radius: 4px;
        /* Rounded border */
    }
    /* Add a hover effect (blue shadow) */
    
    img:hover {
        box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
    }
</style>
<div class="container">
    <div class="rows">
        {% if playlist_list %}
        <div class='col-md-3'>
            <div class="panel panel-primary">
                <div class="panel-body">
                    {% for album in playlist_list %}
                    <!--a href='#' class='thumbnail my-3'>
                        <img src='{{album.logo.url}}' style='height:200px;width:300px'>
                        <p style="padding:10px;color:blue;font-size:20px;font-family:'Permanent Marker'">
                            <strong>{{album.title}}</strong><br>
                        </p>
                        <button class="btn btn-primary" type="button">
                                View Details
                            </button>
                    </a-->
                    <div class="card my-3" style="width: 18rem;">
                        <img class="card-img-top" src="{{album.logo.url}}" style="height:300px" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{album.title}}</h5>
                            <a href="/detailview/{{request.user.id}}/{{album.pid}}" class="btn btn-primary">View Details</a>
                            <a class="btn btn-danger" href="/editplaylist/{{album.pid}}">
                                <span class="fas fa-edit"></span>
                            </a>
                            <a class="btn btn-danger" href="/deleteplaylist/{{album.pid}}" onclick="return confirm('Are you sure you want to delete this playlist')">
                                <span class="fa fa-trash"></span>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        <a href="#">
        <center><img class="mt-3" src="https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_itunes-512.png"></center>
        </a>
        {% if user.is_authenticated %}
        <a class="btn btn-info mt-3" href="/createplaylist">+ Add PlayList</a>
        {% endif%}

    </div>
</div>
</div>
{% endblock %}

playlist/templates/playlist/searchuser.html
{% extends 'login/basic.html' %}
{% block title%} searchusers {% endblock %}
{% block body%}
{% load auth_extras %}
<div class="container">
{% if follow %}
{% for user in users%}
<div class="jumbotron my-3 border border-success" style="width:400px;">
  <center><h1 class="display-6">{{user.username}}</h1>
  <img class="rounded-circle account-img" src="{{ user.profile.image.url }}"></center>
  <hr class="my-4">
  <p class="lead">
    <h3>Followers:{{user.profile.followers.all|length}}</h3>
    <h3>Following:{{user.profile.following.all|length}}</h3>
    {% ifnotequal request.user.username user.username %}
    {% if request.user|is_follower:user%}
    <a class="btn btn-primary btn-lg" href="/unfollow/{{user.id}}" role="button">Unfollow</a>
    {%else%}
    <a class="btn btn-primary btn-lg" href="/follow/{{user.id}}" role="button">Follow</a>
    {%endif%}
    {%endifnotequal%}
    <a class="btn btn-primary btn-lg mx-3" href="/userdashboard/{{user.id}}" role="button">View Details</a>
  </p>
</div>
{% endfor %}
{%else%}

{% for f in followers%}
  <div class="jumbotron my-3 border border-success" style="width:400px;">
  <center><h1 class="display-6">{{f.username}}</h1>
  <img class="rounded-circle account-img" src="{{ f.profile.image.url }}"></center>
  <hr class="my-4">
  <p class="lead">
    <h3>Followers:{{f.profile.followers.all|length}}</h3>
    <h3>Following:{{f.profile.following.all|length}}</h3>
    <a class="btn btn-primary btn-lg" href="/rejectrequest/{{f.id}}" role="button">Reject Request</a>
  </p>
  </div>
{%endfor%}
{%endif%}
</div>
{% endblock %}